title: <p align= "center"> Nagaraju Oruganti </p>
logo: /assets/img/img_profile.jpeg
description: 
<p align="center">
  <a href="https://github.com/nagaraju-oruganti">GitHub</a>
  <br>   
  I'm working on Data Science, NLP, and RL problems.
  <br>
</p>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
